import { createContext, useContext, useMemo, useState } from "react";

export type LanguageCode = "zh" | "en" | "ja" | "th";

type TranslationMap = Record<LanguageCode, string>;
interface TranslationBranch {
  [key: string]: TranslationMap | TranslationBranch;
}
type TranslationNode = TranslationMap | TranslationBranch;

type LanguageContextValue = {
  language: LanguageCode;
  setLanguage: (language: LanguageCode) => void;
  t: (path: string) => string;
};

const translations: TranslationBranch = {
  common: {
    platformName: {
      zh: "CP-AI Brain V1.0",
      en: "CP-AI Brain V1.0",
      ja: "CP-AI Brain V1.0",
      th: "CP-AI Brain V1.0",
    },
    platformTagline: {
      zh: "农牧全产业链量化与智能决策平台",
      en: "AI Quant & Intelligent Decision Platform for Agri-Food Chains",
      ja: "農牧フルバリューチェーン向けAI定量意思決定プラットフォーム",
      th: "แพลตฟอร์ม AI เชิงปริมาณและการตัดสินใจอัจฉริยะสำหรับห่วงโซ่เกษตรอาหาร",
    },
    enterPlatform: {
      zh: "进入平台",
      en: "Enter Platform",
      ja: "プラットフォームへ",
      th: "เข้าสู่แพลตฟอร์ม",
    },
    viewTenants: {
      zh: "查看租户",
      en: "View Tenants",
      ja: "テナントを見る",
      th: "ดูผู้เช่า",
    },
    login: {
      zh: "平台登录",
      en: "Platform Login",
      ja: "プラットフォームログイン",
      th: "เข้าสู่ระบบแพลตฟอร์ม",
    },
    demoMode: {
      zh: "演示模式",
      en: "Demo Mode",
      ja: "デモモード",
      th: "โหมดสาธิต",
    },
    roleAdmin: {
      zh: "管理员",
      en: "Administrator",
      ja: "管理者",
      th: "ผู้ดูแลระบบ",
    },
    roleStrategist: {
      zh: "决策者",
      en: "Decision Maker",
      ja: "意思決定者",
      th: "ผู้ตัดสินใจ",
    },
    roleExecutor: {
      zh: "执行者",
      en: "Executor",
      ja: "実行担当",
      th: "ผู้ปฏิบัติ",
    },
    generatedByFormula: {
      zh: "基于量化公式输出",
      en: "Generated by quantified formulas",
      ja: "定量式に基づく出力",
      th: "สร้างจากสูตรเชิงปริมาณ",
    },
    riskHigh: {
      zh: "高风险",
      en: "High Risk",
      ja: "高リスク",
      th: "ความเสี่ยงสูง",
    },
    riskMedium: {
      zh: "中风险",
      en: "Medium Risk",
      ja: "中リスク",
      th: "ความเสี่ยงปานกลาง",
    },
    riskLow: {
      zh: "低风险",
      en: "Low Risk",
      ja: "低リスク",
      th: "ความเสี่ยงต่ำ",
    },
  },
  nav: {
    tenants: {
      zh: "租户选择",
      en: "Tenant Select",
      ja: "テナント選択",
      th: "เลือกผู้เช่า",
    },
    overview: {
      zh: "全链总览",
      en: "Chain Overview",
      ja: "全体概況",
      th: "ภาพรวมทั้งห่วงโซ่",
    },
    pork: {
      zh: "猪事业部",
      en: "Pork Division",
      ja: "豚事業部",
      th: "หน่วยธุรกิจสุกร",
    },
    quant: {
      zh: "量化决策",
      en: "Quant Engine",
      ja: "定量意思決定",
      th: "เอนจินเชิงปริมาณ",
    },
    audit: {
      zh: "审计日志",
      en: "Audit Log",
      ja: "監査ログ",
      th: "บันทึกการตรวจสอบ",
    },
  },
  dashboard: {
    totalView: {
      zh: "全产业链总览大屏",
      en: "Full Value Chain Command View",
      ja: "全産業チェーン統合ダッシュボード",
      th: "แดชบอร์ดภาพรวมทั้งห่วงโซ่อุตสาหกรรม",
    },
    porkCenter: {
      zh: "猪事业部决策中心",
      en: "Pork Decision Center",
      ja: "豚事業部意思決定センター",
      th: "ศูนย์ตัดสินใจธุรกิจสุกร",
    },
    quantTitle: {
      zh: "量化套利决策引擎",
      en: "Quant Arbitrage Engine",
      ja: "定量裁定エンジン",
      th: "เอนจินการตัดสินใจเชิงอาร์บิทราจ",
    },
    auditTitle: {
      zh: "全流程审计与人机协同",
      en: "Human-AI Governance & Audit",
      ja: "人機協調と監査",
      th: "การกำกับดูแลคน-เอไอและการตรวจสอบ",
    },
    kpiUpdated: {
      zh: "数据已刷新",
      en: "Data refreshed",
      ja: "データ更新済み",
      th: "รีเฟรชข้อมูลแล้ว",
    },
    timeRange: {
      zh: "时间维度",
      en: "Time Horizon",
      ja: "時間軸",
      th: "ช่วงเวลา",
    },
    scenarios: {
      zh: "决策方案",
      en: "Decision Scenarios",
      ja: "意思決定シナリオ",
      th: "สถานการณ์การตัดสินใจ",
    },
    actionList: {
      zh: "建议操作列表",
      en: "Recommended Actions",
      ja: "推奨アクション",
      th: "รายการคำแนะนำ",
    },
    inventory: {
      zh: "库存状态",
      en: "Inventory Status",
      ja: "在庫状況",
      th: "สถานะสินค้าคงคลัง",
    },
    auditTrail: {
      zh: "审计留痕",
      en: "Audit Trail",
      ja: "監査証跡",
      th: "บันทึกการตรวจสอบ",
    },
    confirmRisk: {
      zh: "高风险操作确认",
      en: "High-Risk Confirmation",
      ja: "高リスク操作確認",
      th: "ยืนยันการดำเนินการความเสี่ยงสูง",
    },
  },
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

function resolvePath(path: string): TranslationNode | undefined {
  return path.split(".").reduce<TranslationNode | undefined>((acc, key) => {
    if (!acc || !(key in (acc as Record<string, TranslationNode>))) return undefined;
    return (acc as Record<string, TranslationNode>)[key];
  }, translations as TranslationNode);
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<LanguageCode>("zh");

  const value = useMemo<LanguageContextValue>(() => {
    return {
      language,
      setLanguage,
      t: (path: string) => {
        const result = resolvePath(path);
        if (!result) return path;
        if ("zh" in result) {
          const localized = result as TranslationMap;
          return localized[language] ?? localized.zh;
        }
        return path;
      },
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
