import { createContext, useContext, useMemo, useState } from "react";

export type LanguageCode = "zh" | "en" | "ja" | "th";

type TranslationMap = Record<LanguageCode, string>;
interface TranslationBranch {
  [key: string]: TranslationMap | TranslationBranch;
}
type TranslationNode = TranslationMap | TranslationBranch;

type LanguageContextValue = {
  language: LanguageCode;
  setLanguage: (language: LanguageCode) => void;
  t: (path: string) => string;
};

const translations: TranslationBranch = {
  common: {
    platformName: {
      zh: "CP-AI Brain V1.0",
      en: "CP-AI Brain V1.0",
      ja: "CP-AI Brain V1.0",
      th: "CP-AI Brain V1.0",
    },
    platformTagline: {
      zh: "农牧全产业链量化与智能决策平台",
      en: "AI Quant & Intelligent Decision Platform for Agri-Food Chains",
      ja: "農牧フルバリューチェーン向けAI定量意思決定プラットフォーム",
      th: "แพลตฟอร์ม AI เชิงปริมาณและการตัดสินใจอัจฉริยะสำหรับห่วงโซ่เกษตรอาหาร",
    },
    enterPlatform: {
      zh: "进入平台",
      en: "Enter Platform",
      ja: "プラットフォームへ",
      th: "เข้าสู่แพลตฟอร์ม",
    },
    viewTenants: {
      zh: "查看租户",
      en: "View Tenants",
      ja: "テナントを見る",
      th: "ดูผู้เช่า",
    },
    login: {
      zh: "平台登录",
      en: "Platform Login",
      ja: "プラットフォームログイン",
      th: "เข้าสู่ระบบแพลตฟอร์ม",
    },
    demoMode: {
      zh: "演示模式",
      en: "Demo Mode",
      ja: "デモモード",
      th: "โหมดสาธิต",
    },
    roleAdmin: {
      zh: "管理员",
      en: "Administrator",
      ja: "管理者",
      th: "ผู้ดูแลระบบ",
    },
    roleStrategist: {
      zh: "决策者",
      en: "Decision Maker",
      ja: "意思決定者",
      th: "ผู้ตัดสินใจ",
    },
    roleExecutor: {
      zh: "执行者",
      en: "Executor",
      ja: "実行担当",
      th: "ผู้ปฏิบัติ",
    },
    generatedByFormula: {
      zh: "基于量化公式输出",
      en: "Generated by quantified formulas",
      ja: "定量式に基づく出力",
      th: "สร้างจากสูตรเชิงปริมาณ",
    },
    riskHigh: {
      zh: "高风险",
      en: "High Risk",
      ja: "高リスク",
      th: "ความเสี่ยงสูง",
    },
    riskMedium: {
      zh: "中风险",
      en: "Medium Risk",
      ja: "中リスク",
      th: "ความเสี่ยงปานกลาง",
    },
    riskLow: {
      zh: "低风险",
      en: "Low Risk",
      ja: "低リスク",
      th: "ความเสี่ยงต่ำ",
    },
  },
  nav: {
    tenants: {
      zh: "租户选择",
      en: "Tenant Select",
      ja: "テナント選択",
      th: "เลือกผู้เช่า",
    },
    overview: {
      zh: "全链总览",
      en: "Chain Overview",
      ja: "全体概況",
      th: "ภาพรวมทั้งห่วงโซ่",
    },
    cpVenture: {
      zh: "正大创投",
      en: "CP Ventures",
      ja: "CP投資",
      th: "ซีพีเวนเจอร์",
    },
    pork: {
      zh: "猪事业部",
      en: "Pork Division",
      ja: "豚事業部",
      th: "หน่วยธุรกิจสุกร",
    },
    porkMap: {
      zh: "猪事业地图",
      en: "Pork Geo Map",
      ja: "豚事業マップ",
      th: "แผนที่ธุรกิจสุกร",
    },
    quant: {
      zh: "量化决策",
      en: "Quant Engine",
      ja: "定量意思決定",
      th: "เอนจินเชิงปริมาณ",
    },
    ai: {
      zh: "AI 决策",
      en: "AI Decision",
      ja: "AI意思決定",
      th: "การตัดสินใจ AI",
    },
    audit: {
      zh: "审计日志",
      en: "Audit Log",
      ja: "監査ログ",
      th: "บันทึกการตรวจสอบ",
    },
    timeArbitrage: {
      zh: "时间套利",
      en: "Time Arbitrage",
      ja: "時間裁定",
      th: "การทำอาร์บิทราจข้ามเวลา",
    },
    spatialArbitrage: {
      zh: "空间套利",
      en: "Spatial Arbitrage",
      ja: "空間裁定",
      th: "การทำอาร์บิทราจเชิงพื้นที่",
    },
  },
  timeArbitrage: {
    pageTitle: {
      zh: "冻品收储时间套利",
      en: "Frozen Pork Time Arbitrage",
      ja: "冷凍豚肉時間裁定",
      th: "การทำอาร์บิทราจเวลาเนือหมูแช่แข็ง",
    },
    pageDesc: {
      zh: "动态对比当前持有成本与未来抛售预测价的收储利润空间，辅助做出冷冻猪肉收储与出清动作。",
      en: "Dynamically compare holding costs against future sale prices to assist freezing and selling decisions.",
      ja: "現在の保有コストと将来の予想販売価格の裁定利益を動的に比較し、冷凍豚肉の保管と売却をサポートします。",
      th: "เปรียบเทียบต้นทุนการถือครองเทียบกับราคาขายในอนาคตแบบไดนามิก เพื่อช่วยในการตัดสินใจแช่แข็งและขาย",
    },
    paramSetting: {
      zh: "套利参数设置",
      en: "Arbitrage Parameters",
      ja: "裁定パラメータ設定",
      th: "การตั้งค่าพารามิเตอร์อาร์บิทราจ",
    },
    spotPrice: {
      zh: "当前毛猪价 (元/kg)",
      en: "Current Spot Price",
      ja: "現在の毛豚価格",
      th: "ราคาสปอตปัจจุบัน",
    },
    futuresPrice: {
      zh: "未来预期毛猪价 (元/kg)",
      en: "Expected Future Price",
      ja: "将来予想毛豚価格",
      th: "ราคาคาดการณ์ในอนาคต",
    },
    holdingCost: {
      zh: "起储及利息费 (元/kg/月)",
      en: "Monthly Holding Cost",
      ja: "保管および利息 (月額)",
      th: "ต้นทุนการถือครองและดอกเบี้ย (รายเดือน)",
    },
    costLine: {
      zh: "成本保本线 (持有成本)",
      en: "Break-even Line (Holding Cost)",
      ja: "損益分岐点 (保有コスト)",
      th: "เส้นคุ้มทุน (ต้นทุนการถือครอง)",
    },
    profitLine: {
      zh: "未来预测价",
      en: "Predicted Future Price",
      ja: "将来の予想価格",
      th: "ราคาขายคาดการณ์ในอนาคต",
    },
    adviceTitle: {
      zh: "释放利润预测 (元/kg)",
      en: "Profit Release Forecast",
      ja: "利益解放予測",
      th: "การคาดการณ์การปล่อยผลกำไร",
    },
    aiReasoning: {
      zh: "AI 决策推理",
      en: "AI Reasoning",
      ja: "AI 推論",
      th: "การให้เหตุผล AI",
    },
    marketAnalysis: {
      zh: "市场定价分析:",
      en: "Market Analysis:",
      ja: "市場分析:",
      th: "การวิเคราะห์ตลาด:",
    },
    costRecommendation: {
      zh: "收储成本推算:",
      en: "Cost Recommendation:",
      ja: "コスト推算:",
      th: "คำแนะนำต้นทุน:",
    },
    decision: {
      zh: "决 策 建 议:",
      en: "Decision:",
      ja: "策 定 提 案:",
      th: "การติดสินใจ:",
    },
    riskWarning: {
      zh: "风险提示:",
      en: "Risk Warning:",
      ja: "リスク警告:",
      th: "คำเตือนความเสี่ยง:",
    },
  },
  spatialArbitrage: {
    pageTitle: {
      zh: "全域立体空间套利引擎",
      en: "Spatial Arbitrage Engine",
      ja: "空間裁定エンジン",
      th: "เครื่องมืออาร์บิทราจเชิงพื้นที่",
    },
    pageDesc: {
      zh: "打破全国均价思维。利用区域供应能力、路网物流效率与消费价差建立动态套利路由网版。",
      en: "Break the national average pricing model. Generate dynamic routing leveraging regional supply, logistics and consumer price spread.",
      ja: "全国平均価格からの脱却。地域供給力、物流効率、消費価格差を利用した動的な裁定ルート網を構築します。",
      th: "สร้างเส้นทางแบบไดนามิกโดยใช้ความสามารถในการจัดหาในระดับภูมิภาค โลจิสติกส์ และส่วนต่างราคา",
    },
    statTotal: {
      zh: "套利机会",
      en: "Opportunities",
      ja: "裁定機会",
      th: "โอกาสอาร์บิทราจ",
    },
    statBest: {
      zh: "最优路由利润",
      en: "Best Route Profit",
      ja: "最適ルート利益",
      th: "กำไรเส้นทางที่ดีที่สุด",
    },
    statTop5: {
      zh: "Top5路群总利润",
      en: "Top5 Total Profit",
      ja: "上位5ルート総利益",
      th: "กำไรรวม 5 อันดับแรก",
    },
    statAvg: {
      zh: "平均有效价差",
      en: "Avg Spread",
      ja: "平均有効スプレッド",
      th: "ส่วนต่างราคาเฉลี่ย",
    },
    paramsGroup: {
      zh: "参数调控",
      en: "Parameters",
      ja: "パラメータ設定",
      th: "การตั้งค่าพารามิเตอร์",
    },
    tfTransport: {
      zh: "运费基准 (元/km/吨)",
      en: "Transport Cost Base",
      ja: "輸送コスト基準",
      th: "ฐานต้นทุนค่าขนส่ง",
    },
    tfMinProfit: {
      zh: "最低套利阈值 (元/kg)",
      en: "Min Threshold",
      ja: "最小裁定閾値",
      th: "เกณฑ์กำไรขั้นต่ำ",
    },
    tfBatchSize: {
      zh: "批次规模 (吨)",
      en: "Batch Size (T)",
      ja: "バッチサイズ (トン)",
      th: "ขนาดชุดสินค้า (ตัน)",
    },
    mapTitle: {
      zh: "全国猪价与供需热力网",
      en: "National Heatmap",
      ja: "全国豚価格ヒートマップ",
      th: "แผนที่ความร้อนราคา",
    },
    routeTitle: {
      zh: "AI推荐套利路由 — 净利降序",
      en: "AI Rated Routes",
      ja: "AI推奨ルート",
      th: "เส้นทางแนะนำโดย AI",
    },
    tasksTitle: {
      zh: "AI 部门协同工单 — 实时拆解",
      en: "AI Department Tasks",
      ja: "AI 部門協調タスク",
      th: "งานประสานงานแผนก AI",
    },
  },
  dashboard: {
    totalView: {
      zh: "全产业链总览大屏",
      en: "Full Value Chain Command View",
      ja: "全産業チェーン統合ダッシュボード",
      th: "แดชบอร์ดภาพรวมทั้งห่วงโซ่อุตสาหกรรม",
    },
    porkCenter: {
      zh: "猪事业部决策中心",
      en: "Pork Decision Center",
      ja: "豚事業部意思決定センター",
      th: "ศูนย์ตัดสินใจธุรกิจสุกร",
    },
    quantTitle: {
      zh: "量化套利决策引擎",
      en: "Quant Arbitrage Engine",
      ja: "定量裁定エンジン",
      th: "เอนจินการตัดสินใจเชิงอาร์บิทราจ",
    },
    auditTitle: {
      zh: "全流程审计与人机协同",
      en: "Human-AI Governance & Audit",
      ja: "人機協調と監査",
      th: "การกำกับดูแลคน-เอไอและการตรวจสอบ",
    },
    kpiUpdated: {
      zh: "数据已刷新",
      en: "Data refreshed",
      ja: "データ更新済み",
      th: "รีเฟรชข้อมูลแล้ว",
    },
    timeRange: {
      zh: "时间维度",
      en: "Time Horizon",
      ja: "時間軸",
      th: "ช่วงเวลา",
    },
    scenarios: {
      zh: "决策方案",
      en: "Decision Scenarios",
      ja: "意思決定シナリオ",
      th: "สถานการณ์การตัดสินใจ",
    },
    actionList: {
      zh: "建议操作列表",
      en: "Recommended Actions",
      ja: "推奨アクション",
      th: "รายการคำแนะนำ",
    },
    inventory: {
      zh: "库存状态",
      en: "Inventory Status",
      ja: "在庫状況",
      th: "สถานะสินค้าคงคลัง",
    },
    auditTrail: {
      zh: "审计留痕",
      en: "Audit Trail",
      ja: "監査証跡",
      th: "บันทึกการตรวจสอบ",
    },
    confirmRisk: {
      zh: "高风险操作确认",
      en: "High-Risk Confirmation",
      ja: "高リスク操作確認",
      th: "ยืนยันการดำเนินการความเสี่ยงสูง",
    },
  },
};

const LanguageContext = createContext<LanguageContextValue | null>(null);

function resolvePath(path: string): TranslationNode | undefined {
  return path.split(".").reduce<TranslationNode | undefined>((acc, key) => {
    if (!acc || !(key in (acc as Record<string, TranslationNode>))) return undefined;
    return (acc as Record<string, TranslationNode>)[key];
  }, translations as TranslationNode);
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<LanguageCode>("zh");

  const value = useMemo<LanguageContextValue>(() => {
    return {
      language,
      setLanguage,
      t: (path: string) => {
        const result = resolvePath(path);
        if (!result) return path;
        if ("zh" in result) {
          const localized = result as TranslationMap;
          return localized[language] ?? localized.zh;
        }
        return path;
      },
    };
  }, [language]);

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within LanguageProvider");
  }
  return context;
}
