export type VentureDomain =
  | "agri-food"
  | "retail"
  | "telecom"
  | "digital"
  | "property"
  | "pharma"
  | "finance"
  | "strategic";

export type VentureStage =
  | "core"
  | "controlled"
  | "platform"
  | "strategic"
  | "ecosystem";

export type VentureCompany = {
  id: string;
  name: string;
  englishName: string;
  domain: VentureDomain;
  stage: VentureStage;
  depth: number;
  x: number;
  y: number;
  relation: string;
  logoDomain?: string;
  ownershipSummary?: string;
  boardRole?: string;
  cpRole: string;
  participation: string;
  business: string;
  synergy: string;
  geography: string;
  evidence: string;
  sourceUrl: string;
};

export type VentureLink = {
  source: string;
  target: string;
  type: "ownership" | "subsidiary" | "strategic" | "ecosystem" | "value-chain";
  strength: number;
};

export const ventureDomains: Record<VentureDomain, { label: string; short: string; color: string }> = {
  "agri-food": { label: "农牧食品", short: "农食", color: "#22c55e" },
  retail: { label: "零售分销", short: "零售", color: "#f59e0b" },
  telecom: { label: "通信媒体", short: "通信", color: "#38bdf8" },
  digital: { label: "电商数字", short: "数字", color: "#8b5cf6" },
  property: { label: "地产基建", short: "地产", color: "#14b8a6" },
  pharma: { label: "医药生物", short: "医药", color: "#fb7185" },
  finance: { label: "金融银行", short: "金融", color: "#eab308" },
  strategic: { label: "战略投资", short: "战略", color: "#a3e635" },
};

export const ventureStages: Record<VentureStage, { label: string; rank: number; description: string }> = {
  core: { label: "集团母体", rank: 0, description: "正大集团作为资本、产业与协同中心。" },
  controlled: { label: "核心控股/运营", rank: 1, description: "正大长期深度运营，构成产业基本盘。" },
  platform: { label: "平台生态", rank: 2, description: "承接多业务线协同的平台型公司。" },
  strategic: { label: "战略参股/联盟", rank: 3, description: "以资本或战略联盟进入外部平台。" },
  ecosystem: { label: "生态关联", rank: 4, description: "与核心业务形成供应、渠道、技术或场景关系。" },
};

export const cpVentureCompanies: VentureCompany[] = [
  {
    id: "cp-group",
    name: "正大集团",
    englishName: "Charoen Pokphand Group",
    domain: "strategic",
    stage: "core",
    depth: 100,
    x: 50,
    y: 50,
    relation: "集团中心",
    logoDomain: "cpgroupglobal.com",
    ownershipSummary: "家族控制的跨国产业集团母体。",
    cpRole: "资本配置与产业协同中心",
    participation: "母体集团，统筹八大业务线与跨国运营。",
    business: "农牧食品、零售分销、通信媒体、数字、地产、医药、金融等。",
    synergy: "通过食品供应链、零售渠道、通信流量、数字支付和金融资源形成复合生态。",
    geography: "总部泰国，业务覆盖多国和经济体。",
    evidence: "集团官网披露 8 大业务线、23 个国家和经济体、生产工厂和员工规模。",
    sourceUrl: "https://www.cpgroupglobal.com/",
  },
  {
    id: "cpf",
    name: "正大食品",
    englishName: "Charoen Pokphand Foods PCL",
    domain: "agri-food",
    stage: "controlled",
    depth: 96,
    x: 28,
    y: 34,
    relation: "核心食品平台",
    logoDomain: "cpfworldwide.com",
    ownershipSummary: "正大集团体系内核心上市食品平台，公开持股口径会随市场披露更新。",
    cpRole: "正大集团农牧食品业务核心平台。",
    participation: "长期运营与产业控股，覆盖饲料、养殖、加工和食品贸易。",
    business: "畜禽、水产、饲料、食品加工、批发零售和出口。",
    synergy: "为零售、冷链、餐饮和食品品牌提供上游供给基础。",
    geography: "泰国及多国市场。",
    evidence: "集团官网将 CPF 及其子公司列为农牧食品业务核心实体。",
    sourceUrl: "https://www.cpgroupglobal.com/en/about-cp/our-business",
  },
  {
    id: "cp-china-agri",
    name: "正大中国农牧食品",
    englishName: "Agro-Industry and Food Business Group (China)",
    domain: "agri-food",
    stage: "controlled",
    depth: 92,
    x: 18,
    y: 49,
    relation: "中国农牧食品运营",
    cpRole: "中国区端到端农牧食品平台。",
    participation: "深度运营，覆盖饲料、养殖、食品加工和消费交付。",
    business: "中国市场的饲料、畜禽、水产、食品加工与渠道供应。",
    synergy: "连接中国原料、养殖、加工、销售和食品安全追溯体系。",
    geography: "中国。",
    evidence: "集团官网披露中国农牧食品业务覆盖从上游到下游的价值链。",
    sourceUrl: "https://www.cpgroupglobal.com/en/about-cp/our-business",
  },
  {
    id: "chia-tai",
    name: "正大种业/卜蜂农业",
    englishName: "Chia Tai Company Limited",
    domain: "agri-food",
    stage: "platform",
    depth: 78,
    x: 22,
    y: 67,
    relation: "农业投入品与种植技术",
    cpRole: "农作物种子、肥料、植保与农业技术平台。",
    participation: "产业运营与农业科技协同。",
    business: "种子、肥料、作物保护、农业机械和新鲜农产品。",
    synergy: "支撑饲料原料、种植基地和食品安全源头。",
    geography: "泰国及区域市场。",
    evidence: "集团官网农牧食品业务列出 Chia Tai 及其子公司。",
    sourceUrl: "https://www.cpgroupglobal.com/en/about-cp/our-business",
  },
  {
    id: "cp-intertrade",
    name: "正大国际贸易",
    englishName: "C.P. Intertrade",
    domain: "agri-food",
    stage: "platform",
    depth: 72,
    x: 36,
    y: 72,
    relation: "大米/食品/物流",
    cpRole: "粮食贸易和综合物流平台。",
    participation: "产业运营，服务食品贸易和跨境物流。",
    business: "Royal Umbrella 大米、食品贸易和物流服务。",
    synergy: "把农产品采购、加工、贸易和物流连接到正大食品网络。",
    geography: "泰国及国际市场。",
    evidence: "集团官网披露 C.P. Intertrade 经营大米、食品和综合物流。",
    sourceUrl: "https://www.cpgroupglobal.com/en/about-cp/our-business",
  },
  {
    id: "cp-all",
    name: "卜蜂莲花/CP ALL",
    englishName: "CP ALL PCL",
    domain: "retail",
    stage: "controlled",
    depth: 94,
    x: 67,
    y: 31,
    relation: "零售核心平台",
    logoDomain: "cpall.co.th",
    ownershipSummary: "正大集团体系内核心零售上市平台。",
    cpRole: "正大零售分销业务的核心上市平台。",
    participation: "核心运营，经营泰国 7-Eleven，并延伸支付、物流、食品和服务。",
    business: "便利店、即食食品、支付服务、物流、IT、营销和教育。",
    synergy: "为 CPF 和正大食品提供终端渠道、消费数据和供应链履约场景。",
    geography: "泰国为主。",
    evidence: "CP ALL 官网披露其由正大集团设立并经营泰国 7-Eleven。",
    sourceUrl: "https://www.cpall.co.th/en/company-information",
  },
  {
    id: "cp-axtra",
    name: "Makro / CP Axtra",
    englishName: "CP Axtra / Siam Makro",
    domain: "retail",
    stage: "platform",
    depth: 84,
    x: 77,
    y: 42,
    relation: "批发与 B2B 零售",
    cpRole: "CP ALL 体系内的批发和会员制零售平台。",
    participation: "通过 CP ALL 收购 Makro 后形成零售分销协同。",
    business: "会员制批发、食品服务、B2B 分销和供应链。",
    synergy: "承接餐饮、批发客户，增强食品和生鲜分销能力。",
    geography: "泰国及区域市场。",
    evidence: "CP ALL 官网披露 2013 年收购 Siam Makro。",
    sourceUrl: "https://www.cpall.co.th/en/company-information",
  },
  {
    id: "lotus",
    name: "Lotus's / 正大莲花",
    englishName: "C.P. Lotus / Lotus's",
    domain: "retail",
    stage: "platform",
    depth: 80,
    x: 75,
    y: 58,
    relation: "大卖场与购物中心",
    cpRole: "中国和区域零售网络的重要组成。",
    participation: "零售平台运营与渠道协同。",
    business: "超市、大卖场、购物中心和消费品零售。",
    synergy: "连接食品供应链、会员数据、商业地产和消费场景。",
    geography: "中国及东南亚相关市场。",
    evidence: "集团官网将 C.P. Lotus 列为中国零售业务代表。",
    sourceUrl: "https://www.cpgroupglobal.com/en/about-cp/our-business",
  },
  {
    id: "true",
    name: "True Corporation",
    englishName: "True Corporation PCL",
    domain: "telecom",
    stage: "controlled",
    depth: 90,
    x: 52,
    y: 22,
    relation: "通信媒体平台",
    logoDomain: "true.th",
    ownershipSummary: "正大体系深度参与的泰国通信媒体平台，持股口径随 True/DTAC 合并后披露变化。",
    cpRole: "正大通信媒体业务核心平台。",
    participation: "深度运营，提供移动、宽带、电视和数字服务。",
    business: "TrueMove H、TrueOnline、TrueVisions、数字内容与连接服务。",
    synergy: "为零售会员、数字支付、云和 AI 应用提供流量与连接基础。",
    geography: "泰国。",
    evidence: "集团官网披露媒体与通信业务由 True Corporation 运营。",
    sourceUrl: "https://www.cpgroupglobal.com/en/about-cp/our-business",
  },
  {
    id: "ascend",
    name: "Ascend Group",
    englishName: "Ascend Group",
    domain: "digital",
    stage: "platform",
    depth: 82,
    x: 48,
    y: 74,
    relation: "数字与金融科技平台",
    cpRole: "正大电商和数字业务的基础设施平台。",
    participation: "集团官网披露为正大集团子公司，覆盖 fintech、电商、数据中心和区块链。",
    business: "Ascend Money、Ascend Commerce、True IDC、Ascend Bit。",
    synergy: "连接零售支付、会员、云服务、数据中心和数字生活场景。",
    geography: "东南亚。",
    evidence: "集团官网披露 Ascend Group 是 C.P. Group 子公司；Ascend Money 官网介绍其金融科技定位。",
    sourceUrl: "https://www.cpgroupglobal.com/en/about-cp-group/our-business",
  },
  {
    id: "ascend-money",
    name: "Ascend Money",
    englishName: "Ascend Money",
    domain: "digital",
    stage: "ecosystem",
    depth: 70,
    x: 58,
    y: 83,
    relation: "金融科技场景",
    cpRole: "通过 Ascend 体系参与支付和普惠金融场景。",
    participation: "数字生态内运营与场景协同。",
    business: "电子钱包、支付、金融服务和数字生活服务。",
    synergy: "服务 7-Eleven、零售会员、电商和移动互联网场景。",
    geography: "东南亚。",
    evidence: "Ascend Money 官网披露其金融科技和数字支付定位。",
    sourceUrl: "https://www.ascendmoneygroup.com/about",
  },
  {
    id: "true-idc",
    name: "True IDC",
    englishName: "True Internet Data Center",
    domain: "digital",
    stage: "ecosystem",
    depth: 66,
    x: 44,
    y: 88,
    relation: "云与数据中心",
    cpRole: "通过 Ascend/True 体系参与云和数据基础设施。",
    participation: "数字基础设施协同。",
    business: "数据中心、云服务和企业数字基础设施。",
    synergy: "支撑正大零售、通信、金融科技和 AI 数据应用。",
    geography: "泰国及区域市场。",
    evidence: "集团官网披露 Ascend 旗下包括 True IDC。",
    sourceUrl: "https://www.cpgroupglobal.com/en/about-cp-group/our-business",
  },
  {
    id: "cp-land",
    name: "CP Land",
    englishName: "C.P. Land PCL",
    domain: "property",
    stage: "controlled",
    depth: 76,
    x: 30,
    y: 19,
    relation: "地产与基建",
    cpRole: "正大地产和基建业务平台。",
    participation: "深度运营，覆盖住宅、办公、酒店、会展和产业地产。",
    business: "房地产开发、租赁、酒店、会展和建筑资源管理。",
    synergy: "承接商业综合体、园区、零售和冷链基础设施场景。",
    geography: "泰国及区域市场。",
    evidence: "集团官网披露 CP Land 及其子公司经营综合地产。",
    sourceUrl: "https://www.cpgroupglobal.com/en/about-cp-group/our-business",
  },
  {
    id: "shanghai-kinghill",
    name: "上海正大广场",
    englishName: "Shanghai Kinghill / Super Brand Mall",
    domain: "property",
    stage: "platform",
    depth: 69,
    x: 17,
    y: 25,
    relation: "中国商业地产",
    cpRole: "正大在中国商业地产和资产管理的重要节点。",
    participation: "投资开发与资产运营。",
    business: "Super Brand Mall、商业综合体、地产和基础设施投资。",
    synergy: "连接中国消费场景、零售品牌、餐饮和线下流量。",
    geography: "中国上海。",
    evidence: "集团官网披露 Shanghai Kinghill 发展 Super Brand Mall。",
    sourceUrl: "https://www.cpgroupglobal.com/en/about-cp-group/our-business",
  },
  {
    id: "sino-biopharm",
    name: "中国生物制药",
    englishName: "Sino Biopharmaceutical",
    domain: "pharma",
    stage: "strategic",
    depth: 74,
    x: 84,
    y: 23,
    relation: "医药创新平台",
    cpRole: "正大医药业务的重要关联平台。",
    participation: "医药研发、生产和商业化生态参与。",
    business: "肝病、心脑血管、呼吸、骨科等现代药物和健康产品。",
    synergy: "与正大医疗健康、动物健康、生物技术形成研发和市场协同。",
    geography: "中国及国际市场。",
    evidence: "集团官网医药业务列出 Sino Biopharmaceutical。",
    sourceUrl: "https://www.cpgroupglobal.com/en/about-cp/our-business",
  },
  {
    id: "cpbio",
    name: "正大生物",
    englishName: "CPBIO",
    domain: "pharma",
    stage: "platform",
    depth: 68,
    x: 88,
    y: 38,
    relation: "疫苗与生物技术",
    cpRole: "正大生物技术平台。",
    participation: "研发和生产动物及人用疫苗、生物制品。",
    business: "疫苗、动物健康、生物制药和食品安全相关技术。",
    synergy: "支撑农牧食品安全、动物健康和公共健康。",
    geography: "中国及国际市场。",
    evidence: "集团官网医药业务披露 CPBIO 为正大成员。",
    sourceUrl: "https://www.cpgroupglobal.com/en/about-cp/our-business",
  },
  {
    id: "zhengxin-bank",
    name: "正信银行",
    englishName: "Zheng Xin Bank",
    domain: "finance",
    stage: "controlled",
    depth: 73,
    x: 82,
    y: 68,
    relation: "金融银行",
    cpRole: "正大金融银行业务平台。",
    participation: "金融服务运营。",
    business: "面向中小企业、零售客户和农业客户的金融产品。",
    synergy: "为农户、供应商、零售商和产业链伙伴提供资金服务。",
    geography: "中国。",
    evidence: "集团官网披露正信银行为正大金融银行业务代表。",
    sourceUrl: "https://www.cpgroupglobal.com/en/about-cp-group/our-business",
  },
  {
    id: "ping-an",
    name: "中国平安",
    englishName: "Ping An Insurance",
    domain: "finance",
    stage: "strategic",
    depth: 62,
    x: 90,
    y: 81,
    relation: "核心战略投资",
    logoDomain: "pingan.cn",
    ownershipSummary: "2012年从汇丰收购15.57%股权，为当时平安单一最大股东。虽后续有减持及稀释，正大目前仍通过间接持股维持约5%-9%的战略股权。",
    boardRole: "正大集团主席谢吉人（Soopakij Chearavanont）及资深副董事长杨小平自2013年起长期担任平安非执行董事，深度参与治理。",
    cpRole: "通过资本纽带深度进入中国金融、保险与医疗健康生态。",
    participation: "作为核心战略投资方，与平安在金融科技、医疗健康及大农村领域存在长期协作空间。",
    business: "保险、银行、资产管理、医疗健康及金融科技生态。",
    synergy: "与正大医药板块、农牧板块在中国市场的资源整合形成互补。",
    geography: "中国。",
    evidence: "平安保险年报披露正大集团为其主要股东及董事会席位信息。",
    sourceUrl: "https://group.pingan.com/investor_relations/major_shareholders.html",
  },
  {
    id: "citic-group",
    name: "中信集团",
    englishName: "CITIC Group",
    domain: "finance",
    stage: "strategic",
    depth: 73,
    x: 80,
    y: 87,
    relation: "央企战略合作方",
    logoDomain: "citic.com",
    ownershipSummary: "中信集团为中央直管国有综合性集团，并为中信股份绝对控股股东；公开口径显示其长期持有中信股份约六成股权。",
    boardRole: "中信集团通过控股地位主导中信股份治理；正大光明作为第二大股东可派驻董事参与中信股份董事会。",
    cpRole: "正大全球化、金融协同和中国市场项目合作的重要央企伙伴。",
    participation: "非隶属、非母子公司关系；双方以长期战略股东关系和全方位战略合作机制绑定。",
    business: "金融、先进智造、先进材料、新消费、新型城镇化、资源能源、工程承包和海外平台。",
    synergy: "中信全牌照金融、基建和全球网络，与正大农牧食品、零售、康养及东南亚渠道互补，支持跨境投融资、一带一路项目、供应链金融和联合投资。",
    geography: "中国及全球市场。",
    evidence: "中信集团/中信股份公开资料披露其控股地位；2015 年正大与伊藤忠通过正大光明入股中信股份并形成长期战略联盟。",
    sourceUrl: "https://www.citic.com/",
  },
  {
    id: "citic",
    name: "中信股份",
    englishName: "CITIC Limited",
    domain: "strategic",
    stage: "strategic",
    depth: 67,
    x: 68,
    y: 86,
    relation: "正大光明战略持股",
    ownershipSummary: "2015 年正大集团与伊藤忠商事各 50% 合资成立正大光明（CT Bright），合计斥资近 800 亿港元入股中信股份；足额转股后正大光明持有中信股份 20.61%，为第二大股东。中信集团仍约 60% 控股，为绝对控股股东。",
    boardRole: "正大光明可派驻董事进入中信股份董事会；正大集团资深副董事长杨小平担任中信股份非执行董事。",
    cpRole: "正大作为长期核心战略财务+产业股东，参与中信股份治理与产业协同。",
    participation: "战略参股/联盟；正大与中信无上下级隶属关系，也不是母子公司。",
    business: "金融、资源能源、制造、工程承包、地产等综合业务。",
    synergy: "正大农牧食品、零售与东南亚渠道，叠加中信金融、基建、地产、能源和全球平台，再结合伊藤忠商事网络，构建跨国、跨行业的“金三角”协作。",
    geography: "中国及国际市场。",
    evidence: "中信股份年报披露 CT Bright 为其主要股东，及正大、伊藤忠、中信战略联盟协议内容。",
    sourceUrl: "https://www.citic.com/ar2024/en/",
  },
  {
    id: "saic-motor-cp",
    name: "上汽正大",
    englishName: "SAIC Motor-CP",
    domain: "strategic",
    stage: "controlled",
    depth: 71,
    x: 15,
    y: 15,
    relation: "汽车制造合资",
    logoDomain: "mgcars.com",
    ownershipSummary: "正大集团与上海汽车集团（SAIC Motor）的49:51合资企业，共同运营MG名爵品牌。",
    cpRole: "上汽在东南亚最重要的战略合作伙伴。",
    participation: "负责MG名爵品牌在泰国的制造与分销，并建立区域生产基地。",
    business: "汽车生产、销售及售后服务，特别是新能源汽车（EV）的普及。",
    synergy: "利用正大在泰国的政商资源、地产园区及充电网络（如在7-Eleven布局充电桩）推广绿色出行。",
    geography: "泰国（春武里府生产基地）。",
    evidence: "上汽集团官网及泰国工业部披露其合资工厂与生产数据。",
    sourceUrl: "https://www.saicmotor.com/english/latest_news/saic_motor/58759.shtml",
  },
  {
    id: "ant-group",
    name: "蚂蚁集团",
    englishName: "Ant Group",
    domain: "digital",
    stage: "strategic",
    depth: 59,
    x: 52,
    y: 95,
    relation: "数字金融伙伴",
    logoDomain: "antgroup.com",
    ownershipSummary: "公开资料主要显示蚂蚁集团入股正大旗下 Ascend Money；未将其标注为正大持有蚂蚁集团股权的企业。",
    cpRole: "数字支付及普惠金融领域的全球盟友。",
    participation: "蚂蚁集团与正大旗下 Ascend Money 形成股权和战略合作关系，双方围绕支付和金融科技协同。",
    business: "数字支付、金融科技、信贷、理财及全球支付网络（Alipay+）。",
    synergy: "蚂蚁为正大零售（7-Eleven）提供支付技术赋能，正大则协助蚂蚁在东南亚推广TrueMoney支付工具。",
    geography: "中国及全球。",
    evidence: "2016年双方签署战略合作协议，蚂蚁入股Ascend Money。",
    sourceUrl: "https://www.scmp.com/business/companies/article/1977751/jack-mas-ant-financial-plans-buy-20pc-stake-ascend-money",
  },
  {
    id: "hema-fresh",
    name: "盒马鲜生 / 盒马",
    englishName: "Freshippo",
    domain: "retail",
    stage: "ecosystem",
    depth: 61,
    x: 72,
    y: 65,
    relation: "新零售供应链协作",
    logoDomain: "freshippo.com",
    ownershipSummary: "虽然盒马由阿里巴巴全资控股，但正大集团是其核心供应商和“新零售联盟”创始伙伴。",
    cpRole: "盒马全球供应链核心合作伙伴。",
    participation: "战略级商品协作，正大作为核心生鲜供应商，双方共同开发定制化生鲜产品。",
    business: "新零售商超、即时零售及自有品牌生鲜。",
    synergy: "正大农牧的源头供给能力与盒马的数字化终端、算法推荐深度整合（如定制鸡蛋、联名预制菜）。",
    geography: "中国。",
    evidence: "公开报道显示正大集团与盒马签署“新零售大单”，并成立预制菜产业联盟。",
    sourceUrl: "https://www.yicaiglobal.com/news/20230510-07-alibabas-grocery-arm-hema-fresh-forays-into-chinas-premade-food-market",
  },
  {
    id: "honma-golf",
    name: "本间高尔夫",
    englishName: "Honma Golf",
    domain: "retail",
    stage: "strategic",
    depth: 53,
    x: 94,
    y: 45,
    relation: "高端消费品投资",
    logoDomain: "honmagolf.com",
    ownershipSummary: "正大集团主席谢吉人（Soopakij Chearavanont）于2024年11月受委任为该公司非执行董事。",
    cpRole: "布局全球高端运动消费市场。",
    participation: "通过董事会参与，支持该品牌在中国及东南亚高端圈层的扩张。",
    business: "高尔夫球杆、服装及配件的设计、制造与分销。",
    synergy: "正大的零售渠道资源与本间的高端品牌溢价相结合，服务高净值客群。",
    geography: "日本、中国及全球。",
    evidence: "港交所公告（2024112900583）披露谢吉人的委任信息。",
    sourceUrl: "https://www1.hkexnews.hk/listedco/listconews/sehk/2024/1129/2024112900583.pdf",
  },
  {
    id: "altervim",
    name: "Altervim",
    englishName: "Altervim",
    domain: "property",
    stage: "ecosystem",
    depth: 55,
    x: 16,
    y: 82,
    relation: "新能源解决方案",
    cpRole: "正大可再生能源和电动化生态节点。",
    participation: "能源解决方案平台。",
    business: "太阳能、电动化和低碳能源方案。",
    synergy: "为零售门店、物流车队、园区和食品工厂降低能源成本。",
    geography: "泰国及区域市场。",
    evidence: "集团官网披露 Altervim 为正大可再生能源子公司。",
    sourceUrl: "https://www.cpgroupglobal.com/en/about-cp-group/our-business",
  },
  {
    id: "cp-pokphand",
    name: "卜蜂国际 / C.P. Pokphand",
    englishName: "C.P. Pokphand Co. Ltd.",
    domain: "agri-food",
    stage: "controlled",
    depth: 91,
    x: 12,
    y: 58,
    relation: "中国与越南农牧食品平台",
    logoDomain: "cpp.hk",
    ownershipSummary: "公开资料显示 C.P. Pokphand 由 CPF 控制，2025 年 CPF 宣布收购 Itochu 所持 23.8% 股权以实现全资化。",
    cpRole: "中国、越南饲料、养殖、水产和加工食品平台。",
    participation: "通过 CPF/正大体系控股运营，覆盖中国和越南农牧食品价值链。",
    business: "动物饲料、畜禽和水产养殖、增值加工食品。",
    synergy: "补强中国和越南猪禽水产产业链，连接饲料、养殖、加工与渠道。",
    geography: "中国、越南。",
    evidence: "C.P. Pokphand 官网披露其是中国和越南领先农牧食品集团；2025 年公开报道披露 CPF 收购剩余 Itochu 股权。",
    sourceUrl: "https://www.cpp.hk/?route=about_profile",
  },
  {
    id: "cp-vietnam",
    name: "正大越南",
    englishName: "C.P. Vietnam",
    domain: "agri-food",
    stage: "controlled",
    depth: 86,
    x: 10,
    y: 74,
    relation: "越南一体化农牧平台",
    logoDomain: "cp.com.vn",
    ownershipSummary: "C.P. Pokphand 早期披露收购 C.P. Vietnam Livestock 70.82% 权益，后续纳入越南农牧食品平台。",
    cpRole: "越南市场饲料、养殖和食品加工核心平台。",
    participation: "正大体系通过 C.P. Pokphand/CPF 深度运营。",
    business: "畜禽水产饲料、猪禽虾鱼养殖、肉制品和水产加工。",
    synergy: "为东南亚食品供应链提供产能、养殖技术和区域消费市场。",
    geography: "越南。",
    evidence: "C.P. Pokphand 官网披露越南业务覆盖完整农牧食品价值链。",
    sourceUrl: "https://www.cpp.hk/?route=business_vietnam",
  },
  {
    id: "chia-tai-tianqing",
    name: "正大天晴",
    englishName: "Chia Tai Tianqing Pharmaceutical",
    domain: "pharma",
    stage: "platform",
    depth: 71,
    x: 93,
    y: 50,
    relation: "中国创新药平台",
    logoDomain: "cttq.com",
    ownershipSummary: "中国生物制药体系内核心制药企业，属于正大医药业务重要平台。",
    cpRole: "正大医药在中国创新药和仿制药商业化的重要载体。",
    participation: "通过中国生物制药及正大医药体系参与。",
    business: "肝病、肿瘤、呼吸、感染、内分泌等领域药品研发、生产和销售。",
    synergy: "与正大医药、医疗健康和生物技术业务共享研发、渠道和市场资源。",
    geography: "中国。",
    evidence: "中国生物制药及正大医药公开资料长期将正大天晴作为核心制药平台。",
    sourceUrl: "https://www.cttq.com/",
  },
  {
    id: "jd",
    name: "京东集团",
    englishName: "JD.com",
    domain: "digital",
    stage: "ecosystem",
    depth: 58,
    x: 64,
    y: 76,
    relation: "渠道与供应链合作伙伴",
    logoDomain: "jd.com",
    ownershipSummary: "未发现公开可靠资料证明正大集团持有京东集团股权；当前按战略合作/渠道生态关系纳入图谱。",
    cpRole: "与正大食品、京东超市和京东供应链形成渠道与履约协同。",
    participation: "合作关系，不按正大占股企业处理；可作为正大食品在中国线上零售和即时履约的重要生态节点。",
    business: "电商零售、物流供应链、京东超市、生鲜、健康和产业服务。",
    synergy: "正大食品可通过京东超市、冷链和供应链体系提升鲜品触达效率，例如三日鲜鸡蛋和预制菜渠道合作。",
    geography: "中国及国际市场。",
    evidence: "公开报道显示京东超市与正大集团发布鸡蛋争鲜战略，并提及双方长期合作。",
    sourceUrl: "https://www.pai.com.cn/p/01je35vn9ptx0m6y9hn73z18f8",
  },
  {
    id: "cp-robot",
    name: "正大机器人",
    englishName: "CP Robot",
    domain: "digital",
    stage: "platform",
    depth: 61,
    x: 49,
    y: 91,
    relation: "机器人投资主体",
    ownershipSummary: "正大集团旗下机器人业务/投资主体，2025 年 7 月作为战略投资方投资智元机器人，金额未披露。",
    cpRole: "承接正大在具身智能、服务机器人、零售与康养场景的产业投资入口。",
    participation: "已确认战略投资主体，负责连接正大全球零售、康养、食品工厂和数字化转型场景。",
    business: "机器人产业投资、商业场景导入、正大体系数字化与自动化应用协同。",
    synergy: "把正大全球零售、康养、工厂、仓储物流和服务场景开放给机器人企业，推动商业化落地。",
    geography: "中国及正大全球场景网络。",
    evidence: "公开报道显示正大集团旗下正大机器人于 2025 年 7 月完成对智元机器人的战略投资，金额未披露。",
    sourceUrl: "https://www.jfdaily.com/sgh/detail?id=1611844",
  },
  {
    id: "agibot",
    name: "智元机器人",
    englishName: "AgiBot / Zhiyuan Robotics",
    domain: "digital",
    stage: "strategic",
    depth: 66,
    x: 62,
    y: 92,
    relation: "已确认机器人战略投资",
    logoDomain: "agibot.com",
    ownershipSummary: "2025 年 7 月智元机器人获得正大集团旗下正大机器人战略投资，金额未披露；同期还获 LG 电子、未来资产等投资方领投/参与，公开报道提及投后估值约 160 亿元。",
    cpRole: "通过正大机器人进入具身智能/人形机器人生态，并与李开复相关具身智能生态形成技术和产业场景连接。",
    participation: "已确认战略投资，面向零售、康养、商业服务、食品工厂、仓储物流和数字化转型场景探索。",
    business: "具身智能、人形机器人、本体+AI 技术、交互服务、工业智造、商业物流和科研教育。",
    synergy: "正大提供全球零售、康养、食品工厂与商业服务场景，帮助智元机器人商业化落地；智元机器人技术反向赋能正大数字化和自动化转型。",
    geography: "中国及全球化布局。",
    evidence: "公开报道披露智元机器人获得正大机器人战略投资，并提及 LG 电子、未来资产等同期投资方及约 160 亿元估值信息。",
    sourceUrl: "https://www.jfdaily.com/sgh/detail?id=1611844",
  },
  {
    id: "cofco",
    name: "中粮集团",
    englishName: "COFCO Corporation",
    domain: "agri-food",
    stage: "ecosystem",
    depth: 57,
    x: 32,
    y: 86,
    relation: "农业食品战略合作",
    logoDomain: "cofco.com",
    ownershipSummary: "未发现公开资料显示正大持有中粮股权；当前按战略合作伙伴纳入。",
    cpRole: "中国农业食品资源、粮油和供应链协同伙伴。",
    participation: "2024 年正大集团与中粮集团签署战略合作协议。",
    business: "粮油食品、农产品贸易、加工、物流和品牌消费品。",
    synergy: "与正大饲料原料、食品供应链、渠道和中国区农牧食品业务形成互补。",
    geography: "中国及全球农业贸易网络。",
    evidence: "正大集团官网披露 CP Group 与 COFCO 签署战略合作协议。",
    sourceUrl: "https://www.cpgroupglobal.com/en/newsroom/news/275/cp-group-and-cofco-a-leader-in-china-s-agriculture-and-food-industry-have-signed-a-strategic-partnership-agreement",
  },
  {
    id: "itochu",
    name: "伊藤忠商事",
    englishName: "ITOCHU Corporation",
    domain: "strategic",
    stage: "strategic",
    depth: 52,
    x: 56,
    y: 10,
    relation: "历史战略联盟",
    logoDomain: "itochu.co.jp",
    ownershipSummary: "ITOCHU 2025 年公告称与正大 2014 年战略投资解除；截至 2025 年 3 月末，CPG 持有 ITOCHU 0.461%。",
    cpRole: "历史资本联盟和贸易协同伙伴。",
    participation: "2014 年形成战略投资和业务联盟，2025 年解除交叉持股安排但业务联盟继续。",
    business: "综合商社，覆盖食品、能源、纺织、机械、金属、ICT、金融等。",
    synergy: "在原料采购、产品供应、信息获取和全球贸易网络方面与正大互补。",
    geography: "日本及全球。",
    evidence: "ITOCHU 2025 年公告披露与正大战略投资解除，同时业务联盟继续，并披露 CPG 持股 0.461%。",
    sourceUrl: "https://www.itochu.co.jp/en/news/press/2025/250421.html",
  },
];

export const cpVentureLinks: VentureLink[] = [
  { source: "cp-group", target: "cpf", type: "ownership", strength: 0.95 },
  { source: "cp-group", target: "cp-china-agri", type: "ownership", strength: 0.9 },
  { source: "cpf", target: "chia-tai", type: "value-chain", strength: 0.65 },
  { source: "cpf", target: "cp-intertrade", type: "value-chain", strength: 0.7 },
  { source: "cp-group", target: "cp-all", type: "ownership", strength: 0.92 },
  { source: "cp-all", target: "cp-axtra", type: "subsidiary", strength: 0.82 },
  { source: "cp-group", target: "lotus", type: "ecosystem", strength: 0.75 },
  { source: "cp-group", target: "true", type: "ownership", strength: 0.88 },
  { source: "true", target: "ascend", type: "ecosystem", strength: 0.68 },
  { source: "ascend", target: "ascend-money", type: "subsidiary", strength: 0.8 },
  { source: "ascend", target: "true-idc", type: "subsidiary", strength: 0.72 },
  { source: "cp-group", target: "cp-land", type: "ownership", strength: 0.76 },
  { source: "cp-land", target: "shanghai-kinghill", type: "ecosystem", strength: 0.66 },
  { source: "cp-group", target: "sino-biopharm", type: "strategic", strength: 0.72 },
  { source: "sino-biopharm", target: "cpbio", type: "ecosystem", strength: 0.62 },
  { source: "cp-group", target: "zhengxin-bank", type: "ownership", strength: 0.7 },
  { source: "cp-group", target: "ping-an", type: "strategic", strength: 0.85 },
  { source: "cp-group", target: "citic-group", type: "strategic", strength: 0.86 },
  { source: "citic-group", target: "citic", type: "ownership", strength: 0.9 },
  { source: "cp-group", target: "citic", type: "strategic", strength: 0.82 },
  { source: "cp-group", target: "altervim", type: "ecosystem", strength: 0.52 },
  { source: "cp-all", target: "ascend-money", type: "ecosystem", strength: 0.64 },
  { source: "cp-all", target: "cpf", type: "value-chain", strength: 0.78 },
  { source: "true", target: "true-idc", type: "value-chain", strength: 0.76 },
  { source: "citic", target: "zhengxin-bank", type: "ecosystem", strength: 0.36 },
  { source: "cpf", target: "cp-pokphand", type: "ownership", strength: 0.88 },
  { source: "cp-pokphand", target: "cp-vietnam", type: "subsidiary", strength: 0.84 },
  { source: "sino-biopharm", target: "chia-tai-tianqing", type: "subsidiary", strength: 0.7 },
  { source: "cp-all", target: "jd", type: "ecosystem", strength: 0.42 },
  { source: "cp-china-agri", target: "jd", type: "value-chain", strength: 0.56 },
  { source: "cp-group", target: "cp-robot", type: "ownership", strength: 0.66 },
  { source: "cp-robot", target: "agibot", type: "strategic", strength: 0.68 },
  { source: "cp-group", target: "agibot", type: "strategic", strength: 0.58 },
  { source: "jd", target: "agibot", type: "ecosystem", strength: 0.44 },
  { source: "cp-group", target: "cofco", type: "ecosystem", strength: 0.5 },
  { source: "cpf", target: "cofco", type: "value-chain", strength: 0.42 },
  { source: "cp-group", target: "itochu", type: "strategic", strength: 0.46 },
  { source: "itochu", target: "citic", type: "strategic", strength: 0.48 },
  { source: "cp-group", target: "saic-motor-cp", type: "ownership", strength: 0.75 },
  { source: "cp-group", target: "ant-group", type: "strategic", strength: 0.68 },
  { source: "ant-group", target: "ascend-money", type: "strategic", strength: 0.72 },
  { source: "cp-group", target: "honma-golf", type: "strategic", strength: 0.55 },
  { source: "cpf", target: "hema-fresh", type: "value-chain", strength: 0.62 },
  { source: "cp-all", target: "hema-fresh", type: "ecosystem", strength: 0.45 },
  { source: "cp-group", target: "jd", type: "ecosystem", strength: 0.42 },
];

export const cpVentureSources = [
  {
    label: "CP Group official business lines",
    url: "https://www.cpgroupglobal.com/en/about-cp/our-business",
  },
  {
    label: "CP Group homepage metrics",
    url: "https://www.cpgroupglobal.com/",
  },
  {
    label: "CP ALL company profile",
    url: "https://www.cpall.co.th/en/company-information",
  },
  {
    label: "Ascend Money about",
    url: "https://www.ascendmoneygroup.com/about",
  },
  {
    label: "Ping An stake sale report",
    url: "https://www.asiaasset.com/insurance/hsbc-to-sell-entire-stake-in-ping-an-insurance-for-us9-38bn/",
  },
  {
    label: "ITOCHU-CITIC-CP alliance",
    url: "https://www.itochu.co.jp/en/business/alliance/index.html",
  },
  {
    label: "CITIC Group official profile",
    url: "https://www.citic.com/",
  },
  {
    label: "Ping An board governance",
    url: "https://group.pingan.com/en/ir/board-of-supervisors.shtml",
  },
  {
    label: "C.P. Pokphand profile",
    url: "https://www.cpp.hk/?route=about_profile",
  },
  {
    label: "CP Group and COFCO agreement",
    url: "https://www.cpgroupglobal.com/en/newsroom/news/275/cp-group-and-cofco-a-leader-in-china-s-agriculture-and-food-industry-have-signed-a-strategic-partnership-agreement",
  },
  {
    label: "ITOCHU dissolution of strategic investment",
    url: "https://www.itochu.co.jp/en/news/press/2025/250421.html",
  },
  {
    label: "AgiBot CP Robot strategic investment",
    url: "https://www.jfdaily.com/sgh/detail?id=1611844",
  },
  {
    label: "JD and CP fresh egg cooperation",
    url: "https://www.pai.com.cn/p/01je35vn9ptx0m6y9hn73z18f8",
  },
  {
    label: "Ping An board governance",
    url: "https://group.pingan.com/investor_relations/major_shareholders.html",
  },
  {
    label: "SAIC-CP MG Thailand factory information",
    url: "https://www.saicmotor.com/english/latest_news/saic_motor/58759.shtml",
  },
  {
    label: "Ant Group/Alibaba strategic alliance 2016",
    url: "https://www.scmp.com/business/companies/article/1977751/jack-mas-ant-financial-plans-buy-20pc-stake-ascend-money",
  },
  {
    label: "Honma Golf director appointment (Soopakij Chearavanont)",
    url: "https://www1.hkexnews.hk/listedco/listconews/sehk/2024/1129/2024112900583.pdf",
  },
];
